analizar_sentimiento_task:
  description: >
    Analizar el texto de la incidencia proporcionada en la variable {incidencia}.
    Identificar el estado emocional del usuario (frustrado, calmado, apurado, etc.)
    y determinar el nivel de urgencia percibido.
  expected_output: >
    Una única etiqueta de texto que resuma el estado del cliente. 
    Por ejemplo: "URGENTE", "Enfadado", "Normal".
  agent: analista_sentimiento

clasificar_incidencia_task:
  description: >
    Revisar el contenido de la {incidencia} y clasificar la incidencia en una de las categorías técnicas predefinidas.
  expected_output: >
    Una única etiqueta de texto que represente la categoría de la incidencia.
    Por ejemplo: "Redes", "Hardware" o "Software".
  agent: clasificador_incidencias

buscar_soluciones_task:
  description: >
    Utilizando la {incidencia} original y su clasificación, buscar en todas
    las fuentes de conocimiento disponibles (Wiki, Zabbix, historial) para
    encontrar soluciones relevantes. Si no hay fuentes de conocimiento no inventes su contenido.
    Si la incidencia menciona problemas de conectividad o acceso a un servicio, 
    utiliza la herramienta de ping para verificar la disponibilidad de la URL: {url_a_verificar}.
  expected_output: >
    Un informe con el contexto y las posibles soluciones.
    Debe incluir una sección para cada fuente de información consultada
    y un resumen final con los pasos recomendados. Incluye el resultado
    del ping si fue necesario.
  agent: buscador_soluciones