analizar_sentimiento_task:
  description: >
    Analizar el texto de la incidencia proporcionada en la variable {incidencia}.
    Identificar el estado emocional del usuario (frustrado, calmado, apurado, etc.)
    y determinar el nivel de urgencia percibido.
  expected_output: >
    Una única etiqueta de texto que resuma el estado del cliente. 
    Por ejemplo: "URGENTE", "Enfadado", "Normal".
  agent: analista_sentimiento

clasificar_incidencia_task:
  description: >
    Revisar el contenido de la {incidencia} y clasificar la incidencia en una de las categorías técnicas predefinidas.
  expected_output: >
    Una única etiqueta de texto que represente la categoría de la incidencia.
    Por ejemplo: "Redes", "Hardware" o "Software".
  agent: clasificador_incidencias

buscar_soluciones_task:
  description: >
    Utilizando la {incidencia} y su clasificación, investiga posibles soluciones.
    Considera usar la herramienta 'Ping Tool' con la URL {url_a_verificar} si crees que puede ayudar a diagnosticar
    un problema de conectividad a un servicio externo.
    Tu objetivo principal es generar un informe claro y conciso con los pasos a seguir,
    basándote en tu conocimiento de Wikis, Zabbix y tickets históricos.
  expected_output: >
    Un informe de soluciones que incluya:
    1. Un resumen del problema.
    2. El resultado del 'Ping Tool' (solo si decidiste usarlo).
    3. Una lista de pasos de solución recomendados basados en tu conocimiento.
  agent: buscador_soluciones
  