analizar_sentimiento_task:
  description: >
    Analizar el texto de la incidencia proporcionada en la variable {incidencia}.
    Identificar el estado emocional del usuario (frustrado, calmado, apurado, etc.)
    y determinar el nivel de urgencia percibido.
  expected_output: >
    Una única etiqueta de texto que resuma el estado del cliente. 
    Por ejemplo: "URGENTE", "Enfadado", "Normal".
  agent: analista_sentimiento

clasificar_incidencia_task:
  description: >
    Revisar el contenido de la {incidencia} y clasificar la incidencia en una de las categorías técnicas predefinidas.
  expected_output: >
    Una única etiqueta de texto que represente la categoría de la incidencia.
    Por ejemplo: "Redes", "Hardware" o "Software".
  agent: clasificador_incidencias

buscar_soluciones_task:
  description: >
    Tu misión es investigar y proponer una solución para la {incidencia}.
    Para ello, tienes a tu disposición un conjunto de herramientas.
    Revisa la lista de herramientas disponibles y utiliza la o las que consideres más relevantes para diagnosticar y resolver el problema.
    Por ejemplo, si la incidencia trata sobre problemas de conectividad, podrías usar la herramienta de Ping. Si necesitas buscar información en la base de conocimiento, podrías usar la herramienta de Wiki.js.
    Analiza la situación y decide qué herramientas te proporcionarán la mejor información.
  expected_output: >
    Un informe completo y detallado con tus hallazgos y recomendaciones. El informe debe incluir:
    1.  **Contexto del Problema**: Un breve resumen de la incidencia.
    2.  **Herramientas Utilizadas y Resultados**: Una sección donde detalles qué herramientas has usado y qué información has obtenido de cada una.
    3.  **Resumen y Pasos Recomendados**: Un resumen final con una solución clara y los pasos a seguir para el técnico o el usuario.
  agent: buscador_soluciones
